-- MySQL Script generated by MySQL Workbench
-- Fri Jul  8 14:45:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `numero` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `cpf` INT NOT NULL,
  PRIMARY KEY (`numero`),
  I
  CONSTRAINT `fkpedido`
    FOREIGN KEY (`cpf`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idcodproduto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcodproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens` (
  `iditens` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `qtd` VARCHAR(45) NOT NULL,
  `codproduto` INT NOT NULL,
  PRIMARY KEY (`iditens`),
 
  CONSTRAINT `fki`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`pedido` (`numero`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fkit`
    FOREIGN KEY (`codproduto`)
    REFERENCES `mydb`.`produto` (`idcodproduto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
